export declare const AUTOCOMPLETE_OFF: string;
export declare const AUTOCOMPLETE_ON: string;
export declare const AUTOFILL_TOKEN_BILLING: string;
export declare const AUTOFILL_TOKEN_SHIPPING: string;
export declare const AUTOFILL_TOKENS_ADDRESS: string[];
export declare const AUTOFILL_TOKEN_HOME: string;
export declare const AUTOFILL_TOKEN_WORK: string;
export declare const AUTOFILL_TOKEN_MOBILE: string;
export declare const AUTOFILL_TOKEN_FAX: string;
export declare const AUTOFILL_TOKEN_PAGER: string;
export declare const AUTOFILL_TOKENS_CONTACT: string[];
export declare const AUTOFILL_FIELD_STREET_ADDRESS: string;
export declare const AUTOFILL_FIELD_ADDRESS_LINE_1: string;
export declare const AUTOFILL_FIELD_ADDRESS_LINE_2: string;
export declare const AUTOFILL_FIELD_ADDRESS_LINE_3: string;
export declare const AUTOFILL_FIELD_ADDRESS_LEVEL_4: string;
export declare const AUTOFILL_FIELD_ADDRESS_LEVEL_3: string;
export declare const AUTOFILL_FIELD_ADDRESS_LEVEL_2: string;
export declare const AUTOFILL_FIELD_ADDRESS_LEVEL_1: string;
export declare const AUTOFILL_FIELD_NAME: string;
export declare const AUTOFILL_FIELD_HONORIFIC_PREFIX: string;
export declare const AUTOFILL_FIELD_GIVEN_NAME: string;
export declare const AUTOFILL_FIELD_ADDITIONAL_NAME: string;
export declare const AUTOFILL_FIELD_FAMILY_NAME: string;
export declare const AUTOFILL_FIELD_HONORIFIC_SUFFIX: string;
export declare const AUTOFILL_FIELD_NICKNAME: string;
export declare const AUTOFILL_FIELD_USERNAME: string;
export declare const AUTOFILL_FIELD_NEW_PASSWORD: string;
export declare const AUTOFILL_FIELD_CURRENT_PASSWORD: string;
export declare const AUTOFILL_FIELD_ORGANIZATION_TITLE: string;
export declare const AUTOFILL_FIELD_ORGANIZATION: string;
export declare const AUTOFILL_FIELD_COUNTRY: string;
export declare const AUTOFILL_FIELD_COUNTRY_NAME: string;
export declare const AUTOFILL_FIELD_POSTAL_CODE: string;
export declare const AUTOFILL_FIELD_CC_NAME: string;
export declare const AUTOFILL_FIELD_CC_GIVEN_NAME: string;
export declare const AUTOFILL_FIELD_CC_ADDITIONAL_NAME: string;
export declare const AUTOFILL_FIELD_CC_FAMILY_NAME: string;
export declare const AUTOFILL_FIELD_CC_NUMBER: string;
export declare const AUTOFILL_FIELD_CC_EXP: string;
export declare const AUTOFILL_FIELD_CC_EXP_MONTH: string;
export declare const AUTOFILL_FIELD_CC_EXP_YEAR: string;
export declare const AUTOFILL_FIELD_CC_CSC: string;
export declare const AUTOFILL_FIELD_CC_TYPE: string;
export declare const AUTOFILL_FIELD_TRANSACTION_CURRENCY: string;
export declare const AUTOFILL_FIELD_TRANSACTION_AMOUNT: string;
export declare const AUTOFILL_FIELD_LANGUAGE: string;
export declare const AUTOFILL_FIELD_BDAY: string;
export declare const AUTOFILL_FIELD_BDAY_DAY: string;
export declare const AUTOFILL_FIELD_BDAY_MONTH: string;
export declare const AUTOFILL_FIELD_BDAY_YEAR: string;
export declare const AUTOFILL_FIELD_SEX: string;
export declare const AUTOFILL_FIELD_URL: string;
export declare const AUTOFILL_FIELD_PHOTO: string;
export declare const AUTOFILL_FIELDS: string[];
export declare const AUTOFILL_FIELD_TEL: string;
export declare const AUTOFILL_FIELD_TEL_COUNTRY_CODE: string;
export declare const AUTOFILL_FIELD_TEL_NATIONAL: string;
export declare const AUTOFILL_FIELD_TEL_AREA_CODE: string;
export declare const AUTOFILL_FIELD_TEL_LOCAL: string;
export declare const AUTOFILL_FIELD_TEL_LOCAL_PREFIX: string;
export declare const AUTOFILL_FIELD_TEL_LOCAL_SUFFIX: string;
export declare const AUTOFILL_FIELD_TEL_LOCAL_EXTENSION: string;
export declare const AUTOFILL_FIELD_EMAIL: string;
export declare const AUTOFILL_FIELD_IMPP: string;
export declare const AUTOFILL_FIELDS_CONTACT: string[];
export declare class DynamicFormAutoFillService {
    constructor();
    isAddressToken(token: string): boolean;
    isContactField(token: string): boolean;
    isContactToken(token: string): boolean;
    isField(token: string): boolean;
    isSectionToken(token: string): boolean;
    validate(tokens: string): boolean;
}
